/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/clock`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/indicators`; params?: Router.UnknownInputParams; } | { pathname: `/IndicatorsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/locker-sleep`; params?: Router.UnknownInputParams; } | { pathname: `/locker-study`; params?: Router.UnknownInputParams; } | { pathname: `/locker-work`; params?: Router.UnknownInputParams; } | { pathname: `/locker`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/clock`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/indicators`; params?: Router.UnknownOutputParams; } | { pathname: `/IndicatorsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/locker-sleep`; params?: Router.UnknownOutputParams; } | { pathname: `/locker-study`; params?: Router.UnknownOutputParams; } | { pathname: `/locker-work`; params?: Router.UnknownOutputParams; } | { pathname: `/locker`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/clock${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/indicators${`?${string}` | `#${string}` | ''}` | `/IndicatorsScreen${`?${string}` | `#${string}` | ''}` | `/locker-sleep${`?${string}` | `#${string}` | ''}` | `/locker-study${`?${string}` | `#${string}` | ''}` | `/locker-work${`?${string}` | `#${string}` | ''}` | `/locker${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/clock`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/indicators`; params?: Router.UnknownInputParams; } | { pathname: `/IndicatorsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/locker-sleep`; params?: Router.UnknownInputParams; } | { pathname: `/locker-study`; params?: Router.UnknownInputParams; } | { pathname: `/locker-work`; params?: Router.UnknownInputParams; } | { pathname: `/locker`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
